_default:
    @just --list --justfile {{justfile()}}

# where polymer peptide server and its shim are located
WD := "./external_polymer"
BATCHER_WD := "../op-batcher"
go_test_flags := "-timeout=20m -parallel=8"

# build polymer peptide server and its shim under ./external_polymer
build-polymer:
    make -C {{WD}} build

build-op-batcher:
    make -C {{BATCHER_WD}} op-batcher

# Can add extra flags to go test, e.g. `just test-polymer -v -count=1`
# test polymer peptide execution engine; need to `just build-polymer` first if it changes or has not been built
test-polymer *GO_TEST_FLAGS: build-polymer
    go test {{go_test_flags}} --externalL2 {{WD}} -run TestSystemE2E TestConfirmationDepth TestFinalization {{GO_TEST_FLAGS}}

test-polymer-shim *GO_TEST_FLAGS: build-polymer
    cd {{WD}} && go test ./... -v

test-op-batcher *GO_TEST_FLAGS: build-op-batcher
    make -C {{BATCHER_WD}} test

# set up devnet; only need to run once
setup-devnet:
    git submodule update --init --recursive
    make devnet-allocs
